### ISSUE TITLE
To do

### ISSUE THREAD

**Issue by envetn** [envetn/OLAcademy#3]
## To do
- [X] Fix issue with resending form when updating page.
- [X] Add about page
- [ ] optimize database requests
- [X] Add content to footer
- [x] Styling needed in calendar, footer, event and about.
- [x] Add preview on events.
- [x] Add user profile
- [x] Add more validation for user input
- [x] Preview of events on index is only shown for loggedin users. (should show for all)

"- [ ] text"

**Comment by adamgeorgsson** [comment]
structure function files

**Comment by adamgeorgsson** [comment]
Var det någon mer databas request som behövde optimeras? Något i veckokalendern? Jag stänger denna så får du göra en ny issue i så fall
